{% set name = "pycaret" %}
{% set version = "3.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pycaret/pycaret/archive/refs/tags/{{ version }}.tar.gz
  sha256: aa89ed0a5795e05200e0e3d44ec3ee96bfea499d5db2df5e37ce903a5bff6ace

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - ipython >=5.5.0
    - ipywidgets >=7.6.5
    - tqdm >=4.62.0
    - numpy >=1.21, <1.27
    - pandas <2.2.0
    - jinja2 >=3
    - scipy >=1.6.1,<=1.11.4
    - joblib >=1.2.0,<1.4
    - scikit-learn >1.4.0
    - pyod >=1.1.3
    - imbalanced-learn >=0.12.0
    - category_encoders >=2.4.0
    - lightgbm >=3.0.0
    - numba >=0.55.0
    - requests >=2.27.1
    - psutil >=5.9.0
    - markupsafe >=2.0.1
    - importlib-metadata >=4.12.0
    - nbformat >=4.2.0
    - cloudpickle
    - deprecation >=2.1.0
    - python-xxhash
    - wurlitzer
    - matplotlib-base >=3.3.0
    - scikit-plot >=0.3.7
    - yellowbrick >=1.4
    - plotly >=5.14.0
    - python-kaleido >=0.2.1
    - schemdraw ==0.15
    - plotly-resampler >=0.8.3.1
    - statsmodels >=0.12.1
    - sktime ==0.26.0
    - tbats >=1.1.3
    - pmdarima >=2.0.4


test:
  requires:
    - python {{ python_min }}
  imports:
    - pycaret

about:
  home: https://pycaret.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PyCaret - An open source, low-code machine learning library in Python.
  doc_url: https://pycaret.readthedocs.io/en/latest/
  dev_url: https://github.com/pycaret/pycaret

extra:
  recipe-maintainers:
    - melonhead901
    - mpaulonis
