{% set name = "pycaret" %}
{% set version = "2.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c75a200c35532fc242d2436cfb45c2c330b63a0b047852bf88bd7a5ede8f632c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - boruta_py
    - cufflinks-py >=0.17.0
    - gensim <4.0.0
    - imbalanced-learn ==0.7.0
    - ipython
    - ipywidgets
    - joblib
    - kmodes >=0.10.1
    - lightgbm >=2.3.1
    - matplotlib-base
    - mlflow
    - mlxtend >=0.17.0
    - nltk
    - pandas
    - pandas-profiling >=2.8.0
    - plotly >=4.4.1
    - pyldavis
    - pyod
    - python >=3.6
    - scikit-learn >=0.23, <=0.23.2
    - scikit-plot
    - scipy <=1.5.4
    - spacy <2.4.0
    - textblob
    - umap-learn
    - wordcloud
    - yellowbrick >=1.0.1
    - numba <0.55
    - numpy
    - packaging

test:
  imports:
    - pycaret

about:
  home: https://github.com/pycaret/pycaret
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PyCaret - An open source, low-code machine learning library in Python.
  doc_url: https://pycaret.readthedocs.io/en/latest/
  dev_url: https://github.com/pycaret/pycaret

extra:
  recipe-maintainers:
    - melonhead901
    - mpaulonis
