{% set name = "pycaret" %}
{% set version = "2.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34d3c1d42c348f8d0c32e36cda513b2ed1f9cc51b800ed092b8839556ebb53d8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - boruta_py
    - cufflinks-py >=0.17.0
    - gensim <4.0.0
    - imbalanced-learn ==0.7.0
    - ipython
    - ipywidgets
    - joblib
    - kmodes >=0.10.1
    - lightgbm >=2.3.1
    - matplotlib-base
    - mlflow
    - mlxtend >=0.17.0
    - nltk
    - numpy ==1.19.5
    - pandas
    - pandas-profiling >=2.3.0
    - plotly >=4.4.1
    - pyldavis
    - pyod
    - python >=3.6
    - scikit-learn >=0.23
    - scipy <=1.5.4
    - spacy <2.4.0
    - textblob
    - umap-learn
    - wordcloud
    - yellowbrick >=1.0.1
    - scikit-plot
    - packaging

test:
  imports:
    - pycaret

about:
  home: https://github.com/pycaret/pycaret
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PyCaret - An open source, low-code machine learning library in Python.
  doc_url: https://pycaret.org/guide/
  dev_url: https://github.com/pycaret/pycaret

extra:
  recipe-maintainers:
    - melonhead901
