{% set name = "pycaret" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pycaret/pycaret/archive/refs/tags/{{ version }}.tar.gz
  sha256: a89b5b098e4fa11625b34f50296179be3fa5ff2726626a51b235a1b7051a8a84

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ipython >=5.5.0
    - ipywidgets >=7.6.5
    - tqdm >=4.62.0
    - numpy >=1.21, <1.24
    - pandas >=1.3.0, <2.0.0
    - jinja2 >=1.2
    - scipy <2.0.0
    - joblib >=1.2.0
    - scikit-learn >=1.0,<1.3.0
    - pyod >=1.0.8
    - imbalanced-learn >=0.8.1
    - category_encoders >=2.4.0
    - lightgbm >=3.0.0
    - numba >=0.55.0
    - requests >=2.27.1
    - psutil >=5.9.0
    - markupsafe >=2.0.1
    - importlib_metadata >=4.12.0
    - nbformat >=4.2.0
    - cloudpickle
    - deprecation >=2.1.0
    - xxhash
    - wurlitzer
    - matplotlib >=3.3.0
    - scikit-plot >=0.3.7
    - yellowbrick >=1.4
    - plotly >=5.0.0
    - python-kaleido >=0.2.1
    - schemdraw ==0.15
    - plotly-resampler >=0.8.3.1
    - statsmodels >=0.12.1
    - sktime >=0.16.1,!=0.17.1,!=0.17.2,!=0.18.0,<0.22.0
    - tbats >=1.1.3
    - pmdarima >=1.8.0,!=1.8.1,<3.0.0


test:
  imports:
    - pycaret

about:
  home: https://pycaret.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PyCaret - An open source, low-code machine learning library in Python.
  doc_url: https://pycaret.readthedocs.io/en/latest/
  dev_url: https://github.com/pycaret/pycaret

extra:
  recipe-maintainers:
    - melonhead901
    - mpaulonis
