{% set name = "pycaret" %}
{% set version = "2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f0433972994efa5cd8bc6544b8dde8bc9e6b11e2e254501d8279b7f187d26b5e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - catboost
    - cufflinks-py >=0.17.0
    - datefinder >=0.7.0
    - gensim
    - imbalanced-learn
    - ipython
    - ipywidgets
    - joblib
    - kmodes >=0.10.1
    - lightgbm >=2.3.1
    - matplotlib-base
    - mlflow
    - mlxtend
    - nltk
    - numpy >=1.17
    - pandas
    - pandas-profiling >=2.3.0
    - plotly >=4.4.1
    - pyldavis
    - pyod
    - python
    - scikit-learn >=0.23
    - seaborn
    - spacy
    - textblob
    - umap-learn
    - wordcloud
    - xgboost >=0.90
    - yellowbrick >=1.0.1

test:
  imports:
    - pycaret

about:
  home: https://github.com/pycaret/pycaret
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PyCaret - An open source, low-code machine learning library in Python.
  doc_url: https://pycaret.org/guide/
  dev_url: https://github.com/pycaret/pycaret

extra:
  recipe-maintainers:
    - melonhead901
